// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adding_headingNameForFriendlyUrl_from_imagefile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_headingNameForFriendlyUrl_from_imagefile));
        
        string IMigrationMetadata.Id
        {
            get { return "202107291323273_adding_headingNameForFriendlyUrl_from_imagefile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
